# Generated by Django 5.1.4 on 2025-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
