# Generated by Django 5.1.4 on 2025-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_candidate_country_alter_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
    ]
