# Generated by Django 5.1.4 on 2025-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_jobdetails_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='app/img/jobpost'),
        ),
    ]
