# Generated by Django 5.1.4 on 2025-01-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobdetails_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='app/img/company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyemail',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companywebsite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app/img/jobpost'),
        ),
    ]
