# Generated by Django 5.1.4 on 2025-01-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_applylist_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="applylist",
            name="experience",
            field=models.IntegerField(default=0),
        ),
    ]
