# Generated by Django 5.1.4 on 2025-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_applylist_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='experience',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
