# Generated by Django 5.1.4 on 2025-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_applylist_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
