# Generated by Django 5.1.4 on 2025-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(default=''),
        ),
    ]
